git add cmd_git.sh
git add git_add.sh
git add jq_securities/assets/js/app.min.js
git add jq_securities/handlebars/footer_cn.handlebars
git add jq_securities/handlebars/footer_en.handlebars
git add jq_securities/handlebars/footer_hk.handlebars
git add jq_securities/templates/footer_cn.precompiled.js
git add jq_securities/templates/footer_en.precompiled.js
git add jq_securities/templates/footer_hk.precompiled.js
